# 自社用カスタムアプリ（デフォルト）。公開用は shopify.app.public.toml を使用。
# https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "61b474b801b754166b12f0b9cd07f450"
name = "Location Stock - Ciara"
application_url = "https://location-stock-indicator-ciara.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locations,read_products,write_app_proxy,write_products"

[auth]
redirect_urls = [ "https://location-stock-indicator-ciara.onrender.com/api/auth" ]

[app_proxy]
url = "https://location-stock-indicator-ciara.onrender.com/apps/location-stock"
subpath = "location-stock"
prefix = "apps"
